<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>78b62a46-e594-4d8d-a782-fe58776badc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='Main'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>193c3a33-3bfd-464d-aaf2-fdb157ed849c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/drinks2.png</value>
      <webElementGuid>50461f32-6e0e-4217-b1ce-5abd8bf45eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Main</value>
      <webElementGuid>336b1f06-7812-4233-af99-d5a2e1004302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>125</value>
      <webElementGuid>911a9552-04f5-4159-b903-e8f3f015c4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>4b4dad0c-c04a-416f-992d-28fd12d0e6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;wrapper&quot;]/section[@class=&quot;food_section layout_padding-bottom&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;filters_menu&quot;]/a[@class=&quot;active&quot;]/li[1]/img[1]</value>
      <webElementGuid>67a7f109-1b7c-40fc-b64d-a33d6c52a4bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Main'])[3]</value>
      <webElementGuid>7972c647-c646-401a-8018-e4cb6aaf1379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/li/img</value>
      <webElementGuid>39906bf9-8500-4889-bbef-277944066567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/drinks2.png' and @alt = 'Main']</value>
      <webElementGuid>78dd66de-9800-45be-91d3-a202c24c6a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Main'])[4]</value>
      <webElementGuid>5be66c80-80e1-4103-bcad-ee89b385fac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/li/img</value>
      <webElementGuid>be4a1f2e-8ff6-4eec-8b9a-937715819cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/desserts2.png' and @alt = 'Main']</value>
      <webElementGuid>c19690d5-51bb-462e-9107-98644e341c3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
