<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DRINKS</name>
   <tag></tag>
   <elementGuidId>db0406ec-0dd3-4193-941c-d911b005c8ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='APPETIZER'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3fe769ca-ea83-4b6b-b9ad-fc1b6e1a29cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DRINKS</value>
      <webElementGuid>0ab0966a-5554-4026-9301-67026f915dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;wrapper&quot;]/section[@class=&quot;food_section layout_padding-bottom&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;filters_menu&quot;]/a[@class=&quot;active&quot;]/li[1]/span[1]</value>
      <webElementGuid>a2329daf-c0c0-4b57-a601-e1e533baac91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPETIZER'])[1]/following::span[1]</value>
      <webElementGuid>5a4b6bd4-977f-4a7e-928f-bc0851abae57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAINDISK'])[1]/following::span[2]</value>
      <webElementGuid>f44c6f8d-f93b-4803-b802-9a6fec0b225e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DESSERTS'])[1]/preceding::span[1]</value>
      <webElementGuid>1d88b708-ae5f-47f9-bafa-4bd272b91d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Matcha Swiss Roll'])[1]/preceding::span[2]</value>
      <webElementGuid>880e459b-2ee4-4ece-ae76-0c6f431a9eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DRINKS']/parent::*</value>
      <webElementGuid>a2594fe9-f9c0-4bd1-8c4d-38f3864ffa24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/li/span</value>
      <webElementGuid>aa0ec557-4376-4a2a-8ed9-47e82b925772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'DRINKS' or . = 'DRINKS')]</value>
      <webElementGuid>40701043-44ba-4242-a722-36bfea1dcf6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAIN DISK'])[1]/following::span[2]</value>
      <webElementGuid>258ee1d9-c4f9-4e5a-b659-28874fcb6da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tonkotsu ramen'])[1]/preceding::span[2]</value>
      <webElementGuid>26b37fde-e380-453f-8fe6-7e90d0242cf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
