<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>091aaec7-5faa-4145-b510-8ceb1d23c13f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.menu-area-main > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4822c197-9aef-486c-a369-bf0cfd90df52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>image3/store (3).png</value>
      <webElementGuid>954ae7f5-1a82-4b66-9e93-ec67c4f1f740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-layout&quot;]/header[1]/div[@class=&quot;header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-9 col-lg-9 col-md-9 col-sm-9&quot;]/div[@class=&quot;menu-area&quot;]/div[@class=&quot;limit-box&quot;]/nav[@class=&quot;main-menu&quot;]/ul[@class=&quot;menu-area-main&quot;]/form[1]/li[@class=&quot;menu-area-main&quot;]/img[1]</value>
      <webElementGuid>08d518bb-0d03-43f2-b496-4e7c2e9ede95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>ed697eda-81d6-4f04-a1b5-08a8e135eb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3d646240-688a-4059-beef-7f51741df478</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/img</value>
      <webElementGuid>655a409b-0471-446d-8312-de0a6810d2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'image3/store (3).png']</value>
      <webElementGuid>3198f964-f738-412b-9d08-5bcc8e956d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myCarousel']/a[3]/img</value>
      <webElementGuid>a4be6014-52e6-4833-bf15-7a6b3c145a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>e7e7d26a-bc94-4903-a6e7-347b3cc79192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'icon/errow.png']</value>
      <webElementGuid>4df8b3a1-9ddf-4117-9b10-410268ddb06a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
