<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_MENU_food</name>
   <tag></tag>
   <elementGuidId>695ec360-aa37-4b24-85dd-e6f8928dddcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='about']/section/div/ul/li/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.food</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>976c531e-8091-4faa-a41c-a28bf69b6310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>food</value>
      <webElementGuid>d968a410-86c3-45e4-b04d-eb61f91dae2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>image3/maindisk.png</value>
      <webElementGuid>859bd116-bb27-4482-8b94-f57d06ba921e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Main</value>
      <webElementGuid>0f8dcff0-8352-4719-8e48-1b6de4eeec87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>d32266ef-88fd-43fd-8b97-4e713bf059d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>2d3902ed-f6df-4987-ab90-618a4c13d701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;about&quot;)/section[@class=&quot;food_section layout_padding-bottom&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;filters_menu&quot;]/li[@class=&quot;active&quot;]/a[@class=&quot;active&quot;]/img[@class=&quot;food&quot;]</value>
      <webElementGuid>b901ef5c-f61c-4e4d-ba12-292d03e79e10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='about']/section/div/ul/li/a/img</value>
      <webElementGuid>49d9eb61-ebf6-4c35-ab62-2dceed5c11fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Main']</value>
      <webElementGuid>1066a358-1e6d-4eab-8f74-1f61c85b0792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>c9fbb8e0-6bec-4305-967e-f6a96fd2f889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'image3/maindisk.png' and @alt = 'Main']</value>
      <webElementGuid>7197b8cf-9cda-4038-8531-b624bac21dbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
